name: Build

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: darwin build tool cache
      id: darwin-build-tool-cache
      uses: actions/cache@v2
      with:
        path: ~/osxcross
        key: ${{ runner.os }}-darwin-tool
    - name: install darwin build tool
      if: steps.darwin-build-tool-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev cmake libxml2-dev
        rustup target add x86_64-apple-darwin        
        git clone https://github.com/tpoechtrager/osxcross
        cd osxcross
        wget -nc https://s3.dockerproject.org/darwin/v2/MacOSX10.10.sdk.tar.xz
        mv MacOSX10.10.sdk.tar.xz tarballs/
        UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh
        cd ..
    - name: Build
      run: |
        cargo build --verbose --release
        cd target/release
        zip ../../rust_cli_starter_sample-x86_64.zip rust_cli_starter_sample
    - name: Run tests
      run: cargo test --verbose
    - name: Build darwin binary
      run: |
        PATH="$(pwd)/osxcross/target/bin:$PATH"
        cargo build --verbose --release --target x86_64-apple-darwin
        cd target/x86_64-apple-darwin/release
        zip ../../../rust_cli_starter_sample-macos-x86_64.zip rust_cli_starter_sample
    - name: Build Windows binary
      run: |
        sudo apt install mingw-w64 -y
        rustup target add x86_64-pc-windows-gnu
        cargo build --verbose --release --target x86_64-pc-windows-gnu
        cd target/x86_64-pc-windows-gnu
        zip ../../../rust_cli_starter_sample-win-x86_64.zip rust_cli_starter_sample
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rust_cli_starter_sample-x86_64.zip
        asset_name: rust_cli_starter_sample-x86_64.zip
        asset_content_type: application/octet-stream
    - name: Upload macos release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rust_cli_starter_sample-macos-x86_64.zip
        asset_name: rust_cli_starter_sample-macos-x86_64.zip
        asset_content_type: application/octet-stream
    - name: Upload windows release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rust_cli_starter_sample-win-x86_64.zip
        asset_name: rust_cli_starter_sample-win-x86_64.zip
        asset_content_type: application/octet-stream
